### ISSUE TITLE
Formatting for new icons

### ISSUE THREAD

**Issue by mariano3** [developmentseed/collecticons-lib#3]
So when creating these icons and exporting through Adobe Illustrator, I noticed that the _svg_ gets spit out centered (vertically) like so:
![screen shot 2015-07-27 at 4 15 50 pm](https://cloud.githubusercontent.com/assets/10968362/8916628/e2fac346-347a-11e5-88ad-bc1c06744a42.png)

And the original _svg's_ are aligned with the top:
![screen shot 2015-07-27 at 4 16 10 pm](https://cloud.githubusercontent.com/assets/10968362/8916701/4e79b1d6-347b-11e5-94ce-75005b3816b4.png)

I'm just wondering if this creates and issue, and if not I'll carry on bringing them in. @ricardomestre

**Comment by ricardoduplos** [comment]
@mariano3 I don't think this creates an issue. Nevertheless, are you working on top of the template? 

https://github.com/developmentseed/collecticons-lib/blob/master/collecticons-template.svg

**Comment by mariano3** [comment]
@ricardomestre Okay cool. Yea I'm using the template, but my Illustrator spits it out centered for some reason.
